<a href="https://colab.research.google.com/github/shivi13102/Earthquake_analysis/blob/main/earthquake_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv("/content/earthquake_data.csv")
df2 = pd.read_csv("/content/earthquake_1995-2023.csv")

In [ ]:
print(df1.info())
display(df1.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      782 non-null    object
 1   magnitude  782 non-null    float64
 2   date_time  782 non-null    object
 3   cdi        782 non-null    int64
 4   mmi        782 non-null    int64
 5   alert      415 non-null    object
 6   tsunami    782 non-null    int64
 7   sig        782 non-null    int64
 8   net        782 non-null    object
 9   nst        782 non-null    int64
 10  dmin       782 non-null    float64
 11  gap        782 non-null    float64
 12  magType    782 non-null    object
 13  depth      782 non-null    float64
 14  latitude   782 non-null    float64
 15  longitude  782 non-null    float64
 16  location   777 non-null    object
 17  continent  206 non-null    object
 18  country    484 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 116.2+ KB
None

,magnitude,cdi,mmi,tsunami,sig,nst,dmin,gap,depth,latitude,longitude
count,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000
mean,6.941125,4.333760,5.964194,0.388747,870.108696,230.250639,1.325757,25.038990,75.883199,3.538100,52.609199
std,0.445514,3.169939,1.462724,0.487778,322.465367,250.188177,2.218805,24.225067,137.277078,27.303429,117.898886
min,6.500000,0.000000,1.000000,0.000000,650.000000,0.000000,0.000000,0.000000,2.700000,-61.848400,-179.968000
25%,6.600000,0.000000,5.000000,0.000000,691.000000,0.000000,0.000000,14.625000,14.000000,-14.595600,-71.668050
50%,6.800000,5.000000,6.000000,0.000000,754.000000,140.000000,0.000000,20.000000,26.295000,-2.572500,109.426000
75%,7.100000,7.000000,7.000000,1.000000,909.750000,445.000000,1.863000,30.000000,49.750000,24.654500,148.941000
max,9.100000,9.000000,9.000000,1.000000,2910.000000,934.000000,17.654000,239.000000,670.810000,71.631200,179.662000

In [ ]:
print(df2.info())
display(df2.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   date_time  1000 non-null   object
 3   cdi        1000 non-null   int64
 4   mmi        1000 non-null   int64
 5   alert      449 non-null    object
 6   tsunami    1000 non-null   int64
 7   sig        1000 non-null   int64
 8   net        1000 non-null   object
 9   nst        1000 non-null   int64
 10  dmin       1000 non-null   float64
 11  gap        1000 non-null   float64
 12  magType    1000 non-null   object
 13  depth      1000 non-null   float64
 14  latitude   1000 non-null   float64
 15  longitude  1000 non-null   float64
 16  location   994 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 148.6+ KB
None

,magnitude,cdi,mmi,tsunami,sig,nst,dmin,gap,depth,latitude,longitude
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,6.940150,3.605000,6.02700,0.325000,847.915000,193.918000,1.125174,20.926290,74.612541,4.315554,51.486576
std,0.438148,3.328972,1.43399,0.468609,301.802632,239.045858,2.073164,24.415895,130.812590,26.633320,117.478302
min,6.500000,0.000000,1.00000,0.000000,650.000000,0.000000,0.000000,0.000000,2.700000,-61.848400,-179.968000
25%,6.600000,0.000000,5.00000,0.000000,691.000000,0.000000,0.000000,0.000000,16.000000,-13.518500,-71.694450
50%,6.800000,4.000000,6.00000,0.000000,744.000000,0.000000,0.000000,18.000000,29.000000,-2.443500,107.791000
75%,7.100000,7.000000,7.00000,1.000000,874.250000,403.000000,1.549250,27.000000,55.000000,25.167250,148.364750
max,9.100000,9.000000,10.00000,1.000000,2910.000000,934.000000,17.654000,239.000000,670.810000,71.631200,179.662000

In [ ]:
display(df1.columns)
display(df2.columns)

Index(['title', 'magnitude', 'date_time', 'cdi', 'mmi', 'alert', 'tsunami',
       'sig', 'net', 'nst', 'dmin', 'gap', 'magType', 'depth', 'latitude',
       'longitude', 'location', 'continent', 'country'],
      dtype='object')

Index(['title', 'magnitude', 'date_time', 'cdi', 'mmi', 'alert', 'tsunami',
       'sig', 'net', 'nst', 'dmin', 'gap', 'magType', 'depth', 'latitude',
       'longitude', 'location', 'continent', 'country'],
      dtype='object')

# Cleaning df1 Table

In [ ]:
columns_to_check = ['date_time','latitude', 'longitude', 'location', 'continent', 'country']

# Check for null values in df1
null_values_df1 = df1[columns_to_check].isnull().sum()

print("Null values in df1:")
print(null_values_df1)

Null values in df1:
date_time      0
latitude       0
longitude      0
location       0
continent    573
country        0
dtype: int64

In [ ]:
display(df1.head(10))

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,green,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.5960,"Malango, Solomon Islands",Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,green,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.7380,"Bengkulu, Indonesia",NaN,NaN
2,M 7.0 -,7.0,12-11-2022 07:09,3,3,green,1,755,us,147,3.125,18.0,mww,579.000,-20.0508,-178.3460,NaN,Oceania,Fiji
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,green,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.1290,"Neiafu, Tonga",NaN,NaN
4,M 6.6 -,6.6,09-11-2022 10:14,0,2,green,1,670,us,131,4.998,27.0,mww,624.464,-25.5948,178.2780,NaN,NaN,NaN
5,M 7.0 - south of the Fiji Islands,7.0,09-11-2022 09:51,4,3,green,1,755,us,142,4.578,26.0,mwb,660.000,-26.0442,178.3810,the Fiji Islands,NaN,NaN
6,M 6.8 - south of the Fiji Islands,6.8,09-11-2022 09:38,1,3,green,1,711,us,136,4.678,22.0,mww,630.379,-25.9678,178.3630,the Fiji Islands,NaN,NaN
7,"M 6.7 - 60 km SSW of Boca Chica, Panama",6.7,20-10-2022 11:57,7,6,green,1,797,us,145,1.151,37.0,mww,20.000,7.6712,-82.3396,"Boca Chica, Panama",NaN,Panama
8,"M 6.8 - 55 km SSW of Aguililla, Mexico",6.8,22-09-2022 06:16,8,7,yellow,1,1179,us,175,2.137,92.0,mww,20.000,18.3300,-102.9130,"Aguililla, Mexico",North America,Mexico
9,"M 7.6 - 35 km SSW of Aguililla, Mexico",7.6,19-09-2022 18:05,9,8,yellow,1,1799,us,271,1.153,69.0,mww,26.943,18.3667,-103.2520,"Aguililla, Mexico",North America,Mexico

In [ ]:
# Use a regular expression to split 'location' into 'location' and 'country' only if a comma exists
df1[['location', 'country']] = df1['location'].str.extract(r'^\s*([^,]+)\s*(?:,\s*(.*))?$', expand=True)

# Fill empty 'country' values with an empty string
df1['country'] = df1['country'].fillna("")

# Verify the changes
display(df1.head(10))

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,green,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.5960,Malango,Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,green,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.7380,Bengkulu,NaN,Indonesia
2,M 7.0 -,7.0,12-11-2022 07:09,3,3,green,1,755,us,147,3.125,18.0,mww,579.000,-20.0508,-178.3460,NaN,Oceania,
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,green,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.1290,Neiafu,NaN,Tonga
4,M 6.6 -,6.6,09-11-2022 10:14,0,2,green,1,670,us,131,4.998,27.0,mww,624.464,-25.5948,178.2780,NaN,NaN,
5,M 7.0 - south of the Fiji Islands,7.0,09-11-2022 09:51,4,3,green,1,755,us,142,4.578,26.0,mwb,660.000,-26.0442,178.3810,the Fiji Islands,NaN,
6,M 6.8 - south of the Fiji Islands,6.8,09-11-2022 09:38,1,3,green,1,711,us,136,4.678,22.0,mww,630.379,-25.9678,178.3630,the Fiji Islands,NaN,
7,"M 6.7 - 60 km SSW of Boca Chica, Panama",6.7,20-10-2022 11:57,7,6,green,1,797,us,145,1.151,37.0,mww,20.000,7.6712,-82.3396,Boca Chica,NaN,Panama
8,"M 6.8 - 55 km SSW of Aguililla, Mexico",6.8,22-09-2022 06:16,8,7,yellow,1,1179,us,175,2.137,92.0,mww,20.000,18.3300,-102.9130,Aguililla,North America,Mexico
9,"M 7.6 - 35 km SSW of Aguililla, Mexico",7.6,19-09-2022 18:05,9,8,yellow,1,1799,us,271,1.153,69.0,mww,26.943,18.3667,-103.2520,Aguililla,North America,Mexico

In [ ]:
# Delete rows where 'location' column is null in both dataframes
df1 = df1[df1['location'].notnull()]

# Verify by checking the number of null values again
null_values_df1_cleaned = df1['location'].isnull().sum()

# Print the cleaned dataframes' summary
print(f"Null values in 'location' for df1 after cleaning: {null_values_df1_cleaned}")

Null values in 'location' for df1 after cleaning: 0

In [ ]:
display(df1)

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,green,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.596,Malango,Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,green,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.738,Bengkulu,NaN,Indonesia
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,green,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.129,Neiafu,NaN,Tonga
5,M 7.0 - south of the Fiji Islands,7.0,09-11-2022 09:51,4,3,green,1,755,us,142,4.578,26.0,mwb,660.000,-26.0442,178.381,the Fiji Islands,NaN,
6,M 6.8 - south of the Fiji Islands,6.8,09-11-2022 09:38,1,3,green,1,711,us,136,4.678,22.0,mww,630.379,-25.9678,178.363,the Fiji Islands,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,"M 7.7 - 28 km SSW of Puerto El Triunfo, El Sal...",7.7,13-01-2001 17:33,0,8,NaN,0,912,us,427,0.000,0.0,mwc,60.000,13.0490,-88.660,Puerto El Triunfo,NaN,El Salvador
778,"M 6.9 - 47 km S of Old Harbor, Alaska",6.9,10-01-2001 16:02,5,7,NaN,0,745,ak,0,0.000,0.0,mw,36.400,56.7744,-153.281,Old Harbor,North America,Alaska
779,"M 7.1 - 16 km NE of Port-Olry, Vanuatu",7.1,09-01-2001 16:49,0,7,NaN,0,776,us,372,0.000,0.0,mwb,103.000,-14.9280,167.170,Port-Olry,NaN,Vanuatu
780,"M 6.8 - Mindanao, Philippines",6.8,01-01-2001 08:54,0,5,NaN,0,711,us,64,0.000,0.0,mwc,33.000,6.6310,126.899,Mindanao,NaN,Philippines
781,"M 7.5 - 21 km SE of Lukatan, Philippines",7.5,01-01-2001 06:57,0,7,NaN,0,865,us,324,0.000,0.0,mwc,33.000,6.8980,126.579,Lukatan,NaN,Philippines

In [ ]:
# Reorder columns in df1
columns = list(df1.columns)
columns.remove('country')
columns.insert(columns.index('location') + 1, 'country')
df1 = df1[columns]

display(df1.head())

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,country,continent
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,green,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.596,Malango,Solomon Islands,Oceania
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,green,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.738,Bengkulu,Indonesia,NaN
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,green,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.129,Neiafu,Tonga,NaN
5,M 7.0 - south of the Fiji Islands,7.0,09-11-2022 09:51,4,3,green,1,755,us,142,4.578,26.0,mwb,660.000,-26.0442,178.381,the Fiji Islands,,NaN
6,M 6.8 - south of the Fiji Islands,6.8,09-11-2022 09:38,1,3,green,1,711,us,136,4.678,22.0,mww,630.379,-25.9678,178.363,the Fiji Islands,,NaN

In [ ]:
columns_to_check = ['title', 'magnitude', 'date_time', 'cdi', 'mmi', 'alert', 'tsunami', 'sig', 'net', 'nst', 'dmin', 'gap', 'magType', 'depth']

# Check for null values in df1
null_values_df1 = df1[columns_to_check].isnull().sum()

print("Null values in df1:")
print(null_values_df1)

Null values in df1:
title          0
magnitude      0
date_time      0
cdi            0
mmi            0
alert        367
tsunami        0
sig            0
net            0
nst            0
dmin           0
gap            0
magType        0
depth          0
dtype: int64

In [ ]:
# Convert 'date-time' column to datetime format for proper sorting
df1['date_time'] = pd.to_datetime(df1['date_time'])

# Sort the data by 'date-time' column
df1 = df1.sort_values(by='date_time', ascending=False)

display(df1.head(10))

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,country,continent
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,2022-11-22 02:03:00,8,7,green,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.5960,Malango,Solomon Islands,Oceania
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,2022-11-18 13:37:00,4,4,green,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.7380,Bengkulu,Indonesia,NaN
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,2022-11-11 10:48:00,5,5,green,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.1290,Neiafu,Tonga,NaN
5,M 7.0 - south of the Fiji Islands,7.0,2022-11-09 09:51:00,4,3,green,1,755,us,142,4.578,26.0,mwb,660.000,-26.0442,178.3810,the Fiji Islands,,NaN
6,M 6.8 - south of the Fiji Islands,6.8,2022-11-09 09:38:00,1,3,green,1,711,us,136,4.678,22.0,mww,630.379,-25.9678,178.3630,the Fiji Islands,,NaN
7,"M 6.7 - 60 km SSW of Boca Chica, Panama",6.7,2022-10-20 11:57:00,7,6,green,1,797,us,145,1.151,37.0,mww,20.000,7.6712,-82.3396,Boca Chica,Panama,NaN
8,"M 6.8 - 55 km SSW of Aguililla, Mexico",6.8,2022-09-22 06:16:00,8,7,yellow,1,1179,us,175,2.137,92.0,mww,20.000,18.3300,-102.9130,Aguililla,Mexico,North America
9,"M 7.6 - 35 km SSW of Aguililla, Mexico",7.6,2022-09-19 18:05:00,9,8,yellow,1,1799,us,271,1.153,69.0,mww,26.943,18.3667,-103.2520,Aguililla,Mexico,North America
10,"M 6.9 - 90 km E of Yujing, Taiwan",6.9,2022-09-18 06:44:00,9,9,yellow,1,887,us,215,0.401,34.0,mww,10.000,23.1444,121.3070,Yujing,Taiwan,Asia
11,"M 6.5 - 96 km SE of Lugu, Taiwan",6.5,2022-09-17 13:41:00,7,7,green,1,756,us,178,0.430,54.0,mww,10.000,23.0290,121.3480,Lugu,Taiwan,Asia

In [ ]:
# Get unique values in the 'country' column for df1
unique_countries_df1 = df1['country'].unique()

# Display unique values
print("Unique values in 'country' column for df1:")
print(unique_countries_df1)

Unique values in 'country' column for df1:
['Solomon Islands' 'Indonesia' 'Tonga' '' 'Panama' 'Mexico' 'Taiwan'
 'Vanuatu' 'Papua New Guinea' 'China' 'Philippines' 'Brazil' 'Peru'
 'Argentina' 'Nicaragua' 'New Caledonia' 'Japan' 'New Zealand' 'USA'
 'Cyprus' 'Timor Leste' 'Haiti' 'Wallis and Futuna' 'Russia' 'Mongolia'
 'Chile' 'Greece' 'Jamaica' 'Turkey' 'Fiji' 'South Sandwich Islands'
 'Australia' 'El Salvador' 'Ecuador' 'Svalbard and Jan Mayen' 'Canada'
 'Venezuela' 'Hawaii' 'Bolivia' 'Honduras' 'Costa Rica' 'Iraq'
 'Russia region' 'New Zealand region' 'Guatemala' 'Botswana' 'Tajikistan'
 'Italy' 'Myanmar' 'Northern Mariana Islands' 'Afghanistan' 'India'
 'India region' 'Aleutian Islands, Alaska' 'Barbados' 'Japan region'
 'Nepal' 'Pakistan' 'Colombia' 'Iran' 'Baja California, Mexico' 'Samoa'
 'Kyrgyzstan' 'Martinique' 'Zimbabwe' 'Democratic Republic'
 'Cayman Islands' 'Algeria' 'Washington']

In [ ]:
# Replace specific values in 'country' column for df1
df1['country'] = df1['country'].replace({'CA': 'California', 'B.C., MX': 'Baja California, Mexico'})

# Verify the changes
print("Updated 'country' column in df1:")
display(df1['country'].unique())

Updated 'country' column in df1:

array(['Solomon Islands', 'Indonesia', 'Tonga', '', 'Panama', 'Mexico',
       'Taiwan', 'Vanuatu', 'Papua New Guinea', 'China', 'Philippines',
       'Brazil', 'Peru', 'Argentina', 'Nicaragua', 'New Caledonia',
       'Japan', 'New Zealand', 'USA', 'Cyprus', 'Timor Leste', 'Haiti',
       'Wallis and Futuna', 'Russia', 'Mongolia', 'Chile', 'Greece',
       'Jamaica', 'Turkey', 'Fiji', 'South Sandwich Islands', 'Australia',
       'El Salvador', 'Ecuador', 'Svalbard and Jan Mayen', 'Canada',
       'Venezuela', 'Bolivia', 'Honduras', 'Costa Rica', 'Iraq',
       'Russia region', 'New Zealand region', 'Guatemala', 'Botswana',
       'Tajikistan', 'Italy', 'Myanmar', 'Afghanistan', 'India',
       'India region', 'Barbados', 'Japan region', 'Nepal', 'Pakistan',
       'Colombia', 'Iran', 'Baja California, Mexico', 'Samoa',
       'Kyrgyzstan', 'Martinique', 'Zimbabwe', 'Democratic Republic',
       'Cayman Islands', 'Algeria'], dtype=object)

In [ ]:
# Define the list of countries to filter
countries_to_filter = ['Alaska', 'California', 'Hawaii', 'Idaho', 'Guam','NV Earthquake', 'Northern Mariana Islands', 'Aleutian Islands, Alaska', 'Washington']

# Filter rows in df1
filtered_df1 = df1[df1['country'].isin(countries_to_filter)]

# Display the filtered rows
print("Rows in df1 with 'country' column matching specified values:")
display(filtered_df1)

Rows in df1 with 'country' column matching specified values:

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,country,continent
243,"M 7.7 - Pagan region, Northern Mariana Islands",7.7,2016-07-29 21:18:00,5,6,green,1,971,us,0,3.294,14.0,mww,196.000,18.5429,145.507,Pagan region,Northern Mariana Islands,NaN
290,"M 6.9 - Fox Islands, Aleutian Islands, Alaska",6.9,2015-07-27 04:49:00,4,7,green,1,734,us,0,0.444,39.0,mww,29.000,52.3760,-169.446,Fox Islands,"Aleutian Islands, Alaska",NaN
336,"M 7.9 - Rat Islands, Aleutian Islands, Alaska",7.9,2014-06-23 20:53:00,6,8,green,1,963,us,0,0.133,22.0,mww,109.000,51.8486,178.735,Rat Islands,"Aleutian Islands, Alaska",North America
395,"M 6.8 - Pagan region, Northern Mariana Islands",6.8,2013-05-14 00:32:00,0,3,green,0,711,us,131,0.000,18.0,mww,602.200,18.7280,145.288,Pagan region,Northern Mariana Islands,NaN
737,"M 6.5 - 114 km SSE of San Jose Village, Northe...",6.5,2002-08-14 13:57:00,0,4,NaN,0,650,us,260,0.000,0.0,mwc,30.000,14.1010,146.199,San Jose Village,Northern Mariana Islands,NaN
771,"M 6.8 - 7 km SSE of Longbranch, Washington",6.8,2001-02-28 18:54:00,7,7,NaN,0,1441,uw,67,0.000,31.0,md,51.798,47.1490,-122.727,Longbranch,Washington,North America

In [ ]:
# Define replacements for the 'location' column
location_replacements = {
    'Nikolski': 'Nikolski, Alaska',
    'Chignik': 'Chignik, Alaska',
    'Perryville': 'Perryville, Missouri',
    'Sand Point': 'Sand Point, Idaho',
    'Stanley': 'Stanley, Idaho',
    'Searles Valley': 'Searles Valley, California',
    'Point MacKenzie': 'Point MacKenzie, Alaska',
    'Adak': 'Adak, Alaska',
    'Chiniak': 'Chiniak, Alaska',
    'Attu Station': 'Attu Station, Alaska',
    'Ferndale': 'Ferndale, Washington',
    'Pedro Bay': 'Pedro Bay, Alaska',
    'Ugashik': 'Ugashik, Alaska',
    'Piti Village': 'Piti Village, Guam',
    'Indianola': 'Indianola, Lowa',
    'Atka': 'Atka, Alaska',
    'Edna Bay': 'Edna Bay, Alaska',
    'Big Lagoon': 'Big Lagoon, Florida',
    'San Simeon': 'San Simeon, California',
    'Cantwell': 'Cantwell, Alaska',
    'Merizo Village': 'Merizo Village, Guam',
    'Inarajan Village': 'Inarajan Village, Guam',
    'Kokhanok': 'Kokhanok, Alaska',
    'Old Harbor': 'Old Harbor, Alaska',
    'Monte Cristo Range': 'Monte Cristo Range, Nevada',
    'Leilani Estates': 'Leilani Estates, Hawaii',
    'Puako': 'Puako, Hawaii',
    'Pagan region': 'Pagan region, Northern Mariana Islands',
    'Fox Islands': 'Fox Islands, Alaska',
    'Rat Islands': 'Rat Islands, Alaska',
    'San Jose Village': 'San Jose Village, Northern Mariana Islands',
    'Longbranch': 'Longbranch, Washington'
}

# Replace specific values in 'location' column for df1
df1['location'] = df1['location'].replace(location_replacements)

# Replace specific values in 'country' column
country_replacements = {'Alaska': 'USA', 'California': 'USA', 'Guam': 'USA', 'Idaho': 'USA', 'NV Earthquake': 'USA', 'Hawaii': 'USA',
                        'Northern Mariana Islands': 'USA', 'Aleutian Islands, Alaska': 'USA', 'Washington': 'USA'}
df1['country'] = df1['country'].replace(country_replacements)

# Update 'continent' column to 'North America' wherever 'country' is 'USA' for df1
df1.loc[df1['country'] == 'USA', 'continent'] = 'North America'

# Verify the changes
print("Updated 'location' and 'country' columns in df1:")
print(df1[['location', 'country']].head())

Updated 'location' and 'country' columns in df1:
           location          country
0           Malango  Solomon Islands
1          Bengkulu        Indonesia
3            Neiafu            Tonga
5  the Fiji Islands
6  the Fiji Islands

In [ ]:
# Define the list of countries to filter
countries_to_filter = ['New Caledonia', 'Wallis and Futuna', 'South Sandwich Islands', 'Svalbard and Jan Mayen', 'Martinique', 'Democratic Republic', 'Cayman Islands']

# Filter rows in df1
filtered_df1 = df1[df1['country'].isin(countries_to_filter)]

# Display the filtered rows
print("Rows in df1 with 'country' column matching specified values:")
display(filtered_df1)

Rows in df1 with 'country' column matching specified values:

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,country,continent
23,"M 6.9 - 284 km ESE of Tadine, New Caledonia",6.9,2022-03-30 20:56:00,6,4,green,1,738,us,0,2.697,42.0,mww,10.00,-22.7200,170.2770,Tadine,New Caledonia,NaN
64,"M 6.5 - 265 km SSE of Alo, Wallis and Futuna",6.5,2021-05-21 22:13:00,5,7,green,1,652,us,0,4.518,44.0,mww,10.00,-16.4796,-177.3560,Alo,Wallis and Futuna,NaN
118,"M 6.6 - 131km S of Bristol Island, South Sandw...",6.6,2019-08-27 23:55:00,0,4,green,1,670,us,0,12.896,19.0,mww,16.00,-60.2152,-26.5801,Bristol Island,South Sandwich Islands,NaN
133,"M 6.5 - 83km ENE of Bristol Island, South Sand...",6.5,2019-04-09 17:53:00,0,5,green,1,650,us,0,7.568,18.0,mww,38.00,-58.6262,-25.3040,Bristol Island,South Sandwich Islands,NaN
145,"M 6.6 - 199 km ESE of Tadine, New Caledonia",6.6,2018-12-05 06:43:00,0,4,green,1,670,us,0,2.679,31.0,mww,10.00,-22.0629,169.7330,Tadine,New Caledonia,NaN
146,"M 7.5 - 166 km ESE of Tadine, New Caledonia",7.5,2018-12-05 04:18:00,3,6,green,1,871,us,0,2.405,18.0,mww,10.00,-21.9496,169.4270,Tadine,New Caledonia,NaN
149,"M 6.7 - 120 km NW of Olonkinbyen, Svalbard and...",6.7,2018-11-09 01:49:00,3,4,green,1,693,us,0,7.853,19.0,mww,10.00,71.6312,-11.2431,Olonkinbyen,Svalbard and Jan Mayen,NaN
154,"M 6.5 - 171 km E of Tadine, New Caledonia",6.5,2018-10-16 01:03:00,0,4,green,1,650,us,0,2.109,22.0,mww,17.00,-21.7427,169.5220,Tadine,New Caledonia,NaN
165,"M 7.1 - 238 km ESE of Tadine, New Caledonia",7.1,2018-08-29 03:51:00,2,5,green,1,776,us,0,2.548,23.0,mww,21.43,-22.0295,170.1260,Tadine,New Caledonia,NaN
187,"M 7.0 - 85 km ENE of Tadine, New Caledonia",7.0,2017-11-19 22:43:00,4,6,green,1,771,us,0,0.617,14.0,mww,10.00,-21.3246,168.6710,Tadine,New Caledonia,NaN
188,"M 6.6 - 74 km E of Tadine, New Caledonia",6.6,2017-11-19 15:09:00,4,5,green,1,676,us,0,0.529,21.0,mww,13.00,-21.5027,168.5980,Tadine,New Caledonia,NaN
193,"M 6.6 - 101 km E of Tadine, New Caledonia",6.6,2017-11-01 02:23:00,3,5,green,1,674,us,0,0.788,29.0,mww,22.00,-21.6484,168.8590,Tadine,New Caledonia,NaN
194,"M 6.7 - 132 km E of Tadine, New Caledonia",6.7,2017-10-31 00:42:00,3,4,green,1,691,us,0,1.062,55.0,mww,24.00,-21.6971,169.1480,Tadine,New Caledonia,NaN
309,"M 6.5 - 181 km SSW of Alo, Wallis and Futuna",6.5,2015-04-17 15:52:00,0,5,green,1,650,us,0,3.702,42.0,mww,10.00,-15.8815,-178.6000,Alo,Wallis and Futuna,NaN
334,"M 6.7 - 201 km SSE of Mata-Utu, Wallis and Futuna",6.7,2014-06-29 17:15:00,0,5,green,1,691,us,0,6.713,45.0,mww,18.00,-14.9831,-175.5100,Mata-Utu,Wallis and Futuna,NaN
466,"M 6.8 - 124 km NE of Wé, New Caledonia",6.8,2011-05-10 08:55:00,4,5,NaN,0,734,us,519,0.000,12.5,mww,11.00,-20.2440,168.2260,Wé,New Caledonia,NaN
481,"M 7.0 - 118 km NNE of Tadine, New Caledonia",7.0,2011-01-13 16:16:00,2,5,NaN,0,755,us,578,0.000,13.3,mww,9.00,-20.6280,168.4710,Tadine,New Caledonia,NaN
577,"M 7.4 - 18 km WNW of Basse-Pointe, Martinique",7.4,2007-11-29 19:00:00,7,7,NaN,0,1542,us,663,0.000,13.4,mwb,156.00,14.9440,-61.2740,Basse-Pointe,Martinique,NaN
639,"M 6.8 - 76 km ESE of Kalemie, Democratic Repub...",6.8,2005-12-05 12:19:00,5,7,NaN,0,744,us,561,0.000,20.0,mwc,22.00,-6.2240,29.8300,Kalemie,Democratic Republic,Africa
670,"M 6.8 - 36 km S of George Town, Cayman Islands",6.8,2004-12-14 23:20:00,5,6,NaN,0,858,us,639,0.000,21.8,mwb,10.00,18.9580,-81.4090,George Town,Cayman Islands,NaN
698,"M 7.3 - 201 km ESE of Tadine, New Caledonia",7.3,2003-12-27 16:00:00,0,4,NaN,0,820,us,235,0.000,46.6,mwc,10.00,-22.0150,169.7660,Tadine,New Caledonia,NaN

# Cleaning df2 Table

In [ ]:
# Check for null values in df2
null_values_df2 = df2[columns_to_check].isnull().sum()

print("\nNull values in df2:")
print(null_values_df2)

Null values in df2:
latitude       0
longitude      0
location       6
continent    716
country      349
dtype: int64

In [ ]:
df2[['location', 'country']] = df2['location'].str.extract(r'^\s*([^,]+)\s*(?:,\s*(.*))?$', expand=True)

df2['country'] = df2['country'].fillna("")

display(df2.head(15))

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,Sola,NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,Intipucá,NaN,El Salvador
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,Loncopué,South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,Sand Point,NaN,Alaska
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,
5,"M 6.6 - 277 km NNE of Codrington, Antigua and ...",6.6,10-07-2023 20:28,5,4,green,1,802,us,95,2.454000,37.0,mww,10.000,20.0196,-61.0955,Codrington,NaN,Antigua and Barbuda
6,M 6.9 - Tonga,6.9,02-07-2023 10:27,4,4,green,1,741,us,136,1.179000,23.0,mww,229.000,-17.8530,-174.9370,Tonga,NaN,
7,M 7.2 - south of the Fiji Islands,7.2,15-06-2023 18:06,8,6,green,1,804,us,85,2.590000,24.0,mww,167.404,-22.9824,-177.2080,the Fiji Islands,NaN,
8,M 6.6 - Panama-Colombia border region,6.6,25-05-2023 03:05,6,6,green,1,733,us,50,2.163000,129.0,mww,10.000,8.8894,-77.1231,Panama-Colombia border region,NaN,
9,M 7.1 - southeast of the Loyalty Islands,7.1,20-05-2023 01:51,3,4,green,1,777,us,98,2.812000,56.0,mww,35.981,-23.0622,170.4560,the Loyalty Islands,NaN,
10,M 7.7 - southeast of the Loyalty Islands,7.7,19-05-2023 02:57,5,4,green,1,927,us,277,3.111000,15.0,mww,18.027,-23.2286,170.6940,the Loyalty Islands,NaN,
11,"M 7.6 - 95 km WNW of Hihifo, Tonga",7.6,10-05-2023 16:02,8,6,green,1,907,us,111,3.631000,17.0,mww,210.097,-15.6002,-174.6080,Hihifo,NaN,Tonga
12,M 6.6 - south of the Fiji Islands,6.6,28-04-2023 03:13,0,2,green,0,670,us,52,5.123000,50.0,mww,598.467,-25.2657,178.4240,the Fiji Islands,NaN,
13,"M 7.1 - 170 km SSE of Teluk Dalam, Indonesia",7.1,24-04-2023 20:00,9,7,green,0,838,us,70,2.282000,58.0,mww,15.462,-0.7810,98.5339,Teluk Dalam,NaN,Indonesia
14,"M 7.1 - Kermadec Islands, New Zealand",7.1,24-04-2023 00:41,8,7,green,1,777,us,126,0.708000,23.0,mww,43.063,-30.0249,-177.8970,Kermadec Islands,NaN,New Zealand

In [ ]:
df2_cleaned = df2[df2['location'].notnull()]

null_values_df2_cleaned = df2_cleaned['location'].isnull().sum()

print(f"Null values in 'location' for df2 after cleaning: {null_values_df2_cleaned}")

Null values in 'location' for df2 after cleaning: 0

In [ ]:
display(df2)

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,Sola,NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,Intipucá,NaN,El Salvador
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,Loncopué,South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,Sand Point,NaN,Alaska
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"M 7.1 - 85 km S of Tungor, Russia",7.1,27-05-1995 13:03,0,9,NaN,0,776,us,0,0.000000,0.0,mwb,11.000,52.6290,142.8270,Tungor,Asia,Russia
996,"M 7.7 - 249 km E of Vao, New Caledonia",7.7,16-05-1995 20:12,0,4,NaN,0,912,us,0,0.000000,0.0,mw,20.200,-23.0080,169.9000,Vao,NaN,New Caledonia
997,"M 6.9 - 27 km NNW of Maubara, Timor Leste",6.9,14-05-1995 11:33,0,6,NaN,0,732,us,0,0.000000,0.0,mw,11.200,-8.3780,125.1270,Maubara,NaN,Timor Leste
998,"M 6.6 - 10 km W of Aianí, Greece",6.6,13-05-1995 08:47,0,9,NaN,0,670,us,0,0.000000,0.0,mw,14.000,40.1490,21.6950,Aianí,Europe,Greece
999,"M 7.1 - 14 km NE of Cabatuan, Philippines",7.1,05-05-1995 03:53,0,7,NaN,0,776,us,0,0.000000,0.0,mw,16.000,12.6260,125.2970,Cabatuan,NaN,Philippines

In [ ]:
# Reorder columns in df2
columns = list(df2.columns)
columns.remove('country')
columns.insert(columns.index('location') + 1, 'country')
df2 = df2[columns]

display(df2.head())

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,country,continent
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,Sola,Vanuatu,NaN
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,Intipucá,El Salvador,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,Loncopué,Argentina,South America
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,Sand Point,Alaska,NaN
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,,NaN

In [ ]:
# Convert 'date-time' column to datetime format for proper sorting
df2['date_time'] = pd.to_datetime(df2['date_time'])

# Sort the data by 'date-time' column
df2 = df2.sort_values(by='date_time', ascending=False)

display(df2.head(10))

<ipython-input-90-7aa5c3e3664f>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df2['date_time'] = pd.to_datetime(df2['date_time'])

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,country,continent
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,2023-08-16 12:47:00,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,Sola,Vanuatu,NaN
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,2023-07-19 00:22:00,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,Intipucá,El Salvador,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,2023-07-17 03:05:00,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,Loncopué,Argentina,South America
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,2023-07-16 06:48:00,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,Sand Point,Alaska,NaN
4,M 7.3 - Alaska Peninsula,7.3,2023-07-16 06:48:00,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,,NaN
5,"M 6.6 - 277 km NNE of Codrington, Antigua and ...",6.6,2023-07-10 20:28:00,5,4,green,1,802,us,95,2.454000,37.0,mww,10.000,20.0196,-61.0955,Codrington,Antigua and Barbuda,NaN
6,M 6.9 - Tonga,6.9,2023-07-02 10:27:00,4,4,green,1,741,us,136,1.179000,23.0,mww,229.000,-17.8530,-174.9370,Tonga,,NaN
7,M 7.2 - south of the Fiji Islands,7.2,2023-06-15 18:06:00,8,6,green,1,804,us,85,2.590000,24.0,mww,167.404,-22.9824,-177.2080,the Fiji Islands,,NaN
8,M 6.6 - Panama-Colombia border region,6.6,2023-05-25 03:05:00,6,6,green,1,733,us,50,2.163000,129.0,mww,10.000,8.8894,-77.1231,Panama-Colombia border region,,NaN
9,M 7.1 - southeast of the Loyalty Islands,7.1,2023-05-20 01:51:00,3,4,green,1,777,us,98,2.812000,56.0,mww,35.981,-23.0622,170.4560,the Loyalty Islands,,NaN

In [ ]:
# Define replacements for the 'location' column
location_replacements = {
    'Nikolski': 'Nikolski, Alaska',
    'Chignik': 'Chignik, Alaska',
    'Perryville': 'Perryville, Missouri',
    'Sand Point': 'Sand Point, Idaho',
    'Stanley': 'Stanley, Idaho',
    'Searles Valley': 'Searles Valley, California',
    'Point MacKenzie': 'Point MacKenzie, Alaska',
    'Adak': 'Adak, Alaska',
    'Chiniak': 'Chiniak, Alaska',
    'Attu Station': 'Attu Station, Alaska',
    'Ferndale': 'Ferndale, Washington',
    'Pedro Bay': 'Pedro Bay, Alaska',
    'Ugashik': 'Ugashik, Alaska',
    'Piti Village': 'Piti Village, Guam',
    'Indianola': 'Indianola, Lowa',
    'Atka': 'Atka, Alaska',
    'Edna Bay': 'Edna Bay, Alaska',
    'Big Lagoon': 'Big Lagoon, Florida',
    'San Simeon': 'San Simeon, California',
    'Cantwell': 'Cantwell, Alaska',
    'Merizo Village': 'Merizo Village, Guam',
    'Inarajan Village': 'Inarajan Village, Guam',
    'Kokhanok': 'Kokhanok, Alaska',
    'Old Harbor': 'Old Harbor, Alaska',
    'Monte Cristo Range': 'Monte Cristo Range, Nevada'
}

# Replace specific values in 'location' column for df2
df2['location'] = df2['location'].replace(location_replacements)

# Replace specific values in 'country' column
country_replacements = {'Alaska': 'USA', 'California': 'USA', 'Guam': 'USA', 'Idaho': 'USA', 'NV Earthquake': 'USA'}
df2['country'] = df2['country'].replace(country_replacements)

# Update 'continent' column to 'North America' wherever 'country' is 'USA' for df2
df2.loc[df2['country'] == 'USA', 'continent'] = 'North America'

print("\nUpdated 'location' and 'country' columns in df2:")
print(df2[['location', 'country']].head())

Updated 'location' and 'country' columns in df2:
            location      country
0               Sola      Vanuatu
1           Intipucá  El Salvador
2           Loncopué    Argentina
3  Sand Point, Idaho          USA
4   Alaska Peninsula